### ISSUE TITLE
Remove slingshot to make clj-http-lite dependency-free?

### ISSUE THREAD

**Issue by borkdude** [clj-commons/clj-http-lite#10]
I have a fork of clj-http-lite which can be run with babashka. What I needed to do:

https://github.com/babashka/clj-http-lite/commit/f44ebe45446f0f44f2b73761d102af3da6d0a13e

- remove the dependency on slingshot since that's not available in babashka:
- remove references to `javax.xml` (this assumes a minimal Java version of 1.8)

Would you consider removing slingshot from this fork of clj-http-lite so we can use the "official" martinklepsch/clj-http-lite in babashka?

**Comment by martinklepsch** [comment]
Yes, would consider. 

I think this would be a breaking change which is unfortunate. I would probably be ok with that though. 👍

**Comment by borkdude** [comment]
I think I found a reasonable solution:

https://github.com/clj-commons/clj-http-lite/commit/4f2e2a8a189a1428b64d7deae5c5b7a2df1a4f91

Instead of `throw+` we can simply use `ex-info` + the response in the data. This should behave the same as slingshot's `throw+`. The tests pass and I don't think we introduced any breaking changes with this, so the discussion can be closed imo.
