### ISSUE TITLE
ci: add Windows to test matrix

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-http-lite#21]
In support of #18.

We currently only run our tests on ubuntu.
I'll add Windows into the mix.
We can add macOS at some later date if we see some reason to do so.

I'll also review CI config and update as appropriate, for example:
- update outdated actions
- add Clojure 1.11 to matrix
- replace JDK 16 with JDK 17 in matrix

**Comment by lread** [comment]
I think that we can reasonably stop testing against Clojure 1.7 at this point.
Our jar references Clojure 1.8.0 which implies this our minimum Clojure version.

**Comment by borkdude** [comment]
@lread I suggest using `neil add test` for adding the cognitect test runner.

**Comment by borkdude** [comment]
Oh, wait, that's already been added.

**Comment by borkdude** [comment]
Yes, agreed on the above.

**Comment by lread** [comment]
Thanks for the feedback, it can get lonely sometimes! 🙂
