### ISSUE TITLE
Mocking with clj-http-fake doesn't seem to work

### ISSUE THREAD

**Issue by anderseknert** [clj-commons/clj-http-lite#51]
I'm trying to mock requests with the clj-http-fake library as suggested in the README, but it seems real requests are always sent. Looking at the [implementation](https://github.com/unrelentingtech/clj-http-fake/blob/master/src/clj_http/fake.clj#L193) there it seems to assume the non-lite version of the client, but perhaps I'm simply misunderstanding something?

**Comment by anderseknert** [comment]
No sweat @lread :) While one might need to provide some additional logic if path matching is required, I got by just fine with using `with-redefs`. Perhaps rather than removing the section entirely, we could show an example or two of how to use that for mocking?

**Comment by lread** [comment]
Oh, yeah @anderseknert, if you have a minimal example that works, a README PR would be much appreciated!

**Comment by anderseknert** [comment]
Sure thing! Busy week ahead, but I'll submit something as soon as I can 🙂

**Comment by lread** [comment]
Cool, thanks @anderseknert! If your current usage is public, I can take a stab at a README example if you provide a link.

**Comment by anderseknert** [comment]
PR is up :) Project where I'll be using this is over [here](https://github.com/johanfylling/jarl/). Although the http stuff is still [WIP](https://github.com/johanfylling/jarl/blob/http.send/src/test/cljc/jarl/builtins/http_test.cljc).
