### ISSUE TITLE
add missing PATCH method 

### ISSUE THREAD

**Issue by jasonjckn** [clj-commons/clj-http-lite#74]
there's no http-lite/patch API

and when I tried http-lite/request , I got 
ERROR in metta.schema.plumbing.instruction-router-test/some-optional-instructions-and-some-not (HttpURLConnection.java:601)
Exception: java.net.ProtocolException: Invalid HTTP method: PATCH

part of the HTTP Standard https://www.iana.org/assignments/http-methods/http-methods.xhtml

**Comment by lread** [comment]
Thanks for raising an issue @jasonjckn, did you notice #11?

**Comment by jasonjckn** [comment]
i'll try out later today, given this is a limitation of underlying java libs, i'll close the issue. it's worth noting java.net.http.HttpRequest doesn't have this 'limitation'.

**Comment by lread** [comment]
Yes, that's a good observation @jasonjckn, if you are OK with dropping JDK8 compatibility you might consider libraries based on java.net.HttpRequest. For some alternatives see JDK11+ libraries listed [here](https://github.com/clj-commons/clj-http-lite/blob/master/doc/01-user-guide.adoc#interesting-alternatives).
